### ISSUE TITLE
Phantom, Coinbase, Atomic.. Solana wallets

### ISSUE THREAD

**Issue by samuel2629** [WalletConnect/WalletConnectModalFlutter#45]
Hi,

First of all thank you for the amazing job. Do you plan to support Phantom soon?
Trying to connect and sign message through Solana but the two main wallets are not available.

Thank you

**Comment by quetool** [comment]
Hello @samuel2629!
The wallets you don't see listed is are those wallets that doesn't use WalletConnect's secure protocol. It is not on us to add them rather to them use our protocol, once they do it they get listed our SDKs.

That being said, we do support Coinbase Wallet in our AppKit (Web3Modal, not WalletConnectModal) because Coinbase do provide an SDK that we can install on our SDKs and provide functionality, however we still don't support Solana on AppKit Flutter (soon to arrive). As far as I know, Phantom and Atomic they don't provide an SDK so there's nothing we can do about it.

If you want to provide Solana communication then this SDK (WalletConnectModalFlutter) is your best option until we provide support for Solana in our AppKit (migration then will be simple)

Hope this clears the issue out! 👌

**Comment by samuel2629** [comment]
Thank you for the really quick and clear answer.
Just another quick question please : what's the difference between Web3Modal and WalletConnectModal ? You mentioned that Solana should arrive soon on the AppKit (so Web3Modal) should i migrate from WalletConnectModal to Web3Modal to get the last updates the soonest ?

Thank you

**Comment by quetool** [comment]
So, 
WalletConnectModal is a protocol-centric SDK, you get there all the benefits of our chain-agnostic protocol, therefor you can use it with Solana, Polkadot and other non-EVM chains but it is pretty basic UI/UX wise, you'll get a QR code and the list of wallets. For many people that is enough, for other ones we have AppKit...

AppKit (Web3Modal), on the other hand, is a more complex and "cross functional" SDK where you get not only the benefits of our protocol but also 
- Coinbase Wallet integration
- Email/Social Wallets
- SIWE
- Smart Accounts *
- Non-EVM chains *
- On Ramp/Swaps *
And more... you can test it out here https://lab.web3modal.com

However, native mobile SDKs (such as Flutter) of AppKit are a bit behind in comparison with the Web ones so you will not have those ones marked with *

Read more about it here https://walletconnect.com/appkit

Thanks!

**Comment by samuel2629** [comment]
Hey,

Thank you a lot for the clear explanations. I think it might be a good idea to add these in the read.me, anyway thank you again.

**Comment by quetool** [comment]
Totally! Thanks @samuel2629 !
